create table if not exists public.lotto_draws (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  numbers jsonb not null,
  bonus integer not null check (bonus between 1 and 45)
);

grant usage on schema public to anon;
grant select, insert, delete on table public.lotto_draws to anon;
grant usage, select on sequence public.lotto_draws_id_seq to anon;

alter table public.lotto_draws enable row level security;

drop policy if exists "Allow public read access" on public.lotto_draws;
create policy "Allow public read access"
on public.lotto_draws
for select
to anon
using (true);

drop policy if exists "Allow public insert access" on public.lotto_draws;
create policy "Allow public insert access"
on public.lotto_draws
for insert
to anon
with check (true);

drop policy if exists "Allow public delete access" on public.lotto_draws;
create policy "Allow public delete access"
on public.lotto_draws
for delete
to anon
using (true);
