create table if not exists public.lotto_draws (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  numbers jsonb not null,
  bonus integer not null check (bonus between 1 and 45)
);

alter table public.lotto_draws enable row level security;

create policy "Allow public read access"
on public.lotto_draws
for select
to anon
using (true);

create policy "Allow public insert access"
on public.lotto_draws
for insert
to anon
with check (true);

create policy "Allow public delete access"
on public.lotto_draws
for delete
to anon
using (true);
